### ISSUE TITLE
VM_Create on game failed - sv_pure always reverts to "1"!

### ISSUE THREAD

**Issue by wtfbbqhax** [wtfbbqhax/tremulous#11]
I don't know if this a new issue; or is just news to me. Setting `sv_pure 0` is not persistent. This results in a VM_Create failure in src/server code if you have not packaged game.qvm in a pk3.

My expectation is that the server might fallback to the game DLL if a qvm does not exits. - IF NOT THIS Then I at least expect sv_pure to persist between server restarts.

**Comment by megatog615** [comment]
sv_pure always resets to 1. This has been the default behavior since q3a.

**Comment by wtfbbqhax** [comment]
That doesn't mean it's the correct behavior :wink:

**Comment by wtfbbqhax** [comment]
Closing this for now, maybe later
