### ISSUE TITLE
Infinite restart in the client setting random window resizes

### ISSUE THREAD

**Issue by cengique** [wtfbbqhax/tremulous#31]
Using the debug-windows-runtime release, I am unable to start the client because it goes into an infinite loop restarting the UI during startup. On the same machine, the stock GPP and 1.1 Tremulous clients work fine. 

This is on:

```
$ uname -a
Linux antec 3.17.2-gentoo #1 SMP PREEMPT Fri Jan 9 14:28:38 EST 2015 x86_64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz GenuineIntel GNU/Linux
```

running the Xmonad window manager. Tremulous opens a floating window which is not forced to a certain size, but keeps restarting the window. 

Here's an example output from Tremulous. You can see it re-initializing without any errors right after the client opens the ports for listening: [debug-infinite-restart-output.txt](https://github.com/wtfbbqhax/tremulous/files/478337/debug-infinite-restart-output.txt). Here's a copy of the autogen.cfg file: 
[example-autogen-cfg.txt](https://github.com/wtfbbqhax/tremulous/files/478345/example-autogen-cfg.txt)

More specifically, if we grep for mode lines, we get this:

```
$ ../blowfish-wtfbbqhax-debug-windows-runtime/tremulous.x86_64 +set fs_game "test3399"  +set fs_overpath overpath/ +set fs_basepath "basepath/" +set fs_homepath ~/.tremulous-test/ +set cl_renderer "opengl2" +set r_fullscreen "0" |& grep -i 'setting mode'
...setting mode 640x480
...setting mode 636x476
...setting mode 632x472
...setting mode 628x468
[clip]
```

**Workaround**: setting the `r_allowResize` cvar to `"1"` stops the infinite loop.

**Comment by wtfbbqhax** [comment]
iortcw/iortcw#4

@cengique Per original discussion with @Cenguie, the workaround in the above referenced bug works for Tremulous.

**Comment by wtfbbqhax** [comment]
Actually looks like the current code has the "likely" fix from iortcw already. Will wait to see if anyone responds to my cross-post in iortcw.

**Comment by cengique** [comment]
@wtfbbqhax actually the `r_allowResize` workaround did NOT work for your binary, but does work for GPP.

**Comment by wtfbbqhax** [comment]
Oh! Thanks, for the clarification.

**Comment by wtfbbqhax** [comment]
@cengique I don't know what to do about this ATM. Can you provide details of the system you experienced this issue on?
1. Distro
2. Distro release
3. XMonad version

**Comment by cengique** [comment]
1. Distro: Gentoo Base System release 2.2. kernel 3.17.2-gentoo
2. XMonad version: xmonad 0.12
