### ISSUE TITLE
Client fatal crashed: Q_strncpyz: destsize < 1

### ISSUE THREAD

**Issue by cengique** [wtfbbqhax/tremulous#34]
Running Tremulous debug-windows-runtime binary with:

```
./tremulous.x86_64 +set r_allowResize "1" +set fs_homepath ~/.tremulous-gh/ +set fs_basepath /usr/share/games/tremulous/
```

[crash.txt](https://github.com/wtfbbqhax/tremulous/files/518036/crash.txt)

**Comment by wtfbbqhax** [comment]
@cengique Did you move the Tremulous binary? There should be a "gpp" folder in the ZIP containing a "vms-1.2.0-CommitSha-_.pk3" and "data-1.2.0-CommitSha-_.pk3"; these files need to be in the search path.

Edit:

```
Have you tried without `+set fs_homepath` ... and `+set fs_basepath`?
```

**Comment by cengique** [comment]
In the `debug-windows-runtime` release I have a `base/` directory instead with `vms-1.2.0-af661e4-2016-09-05.pk3` inside. If I run it with `+set fs_basepath .`, it loads 

```
./base/vms-1.2.0-af661e4-2016-09-05.pk3 (4 files)
```

but then it crashes with 

```
recursive error after: ^1menu list 'ui/menus.txt' not found, unable to continue!
```

I guess I'm missing the data file?

**Comment by wtfbbqhax** [comment]
@cengique that's another issue, you have ui.qvm loading from vms-1.1.0_pk3 but menus loading from data-1.2.0-_.pk3. 

Renaming the vans-1.2.0*.pk3 to zzz.pk3 should workaround the loading issue. I am working with upstream to resolve this issue already.
