### ISSUE TITLE
Auto-update client/server binaries

### ISSUE THREAD

**Issue by wtfbbqhax** [wtfbbqhax/tremulous#9]
Cherry pick code from [Tremulous-Launcher](https://github.com/GrangerHub/tremulous-launcher)  and plumb it into src/sys/sys_main.c:main(). 
### Outline of run-time expectation:
1. Initialize cvars; check for `autoupdate->integer > 1`
2. Request list of releases from wtfbbqhax/tremulous
3. Download update if available
4. exec new tremulous instance/wait + kill self

**Comment by megatog615** [comment]
Make sure you only auto update if you're running an official build.

**Comment by wtfbbqhax** [comment]
@megatog615 absolutely! 

As I flesh out the infrastructure that will feed the auto-updater additional release "channels" will be added (e.g., beta, stable, nightly).  Users will be able to choose which release channel they are subscribed to.
